<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\wechatauto\WeChatAuto.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="models\PP-OCRv6_det_small.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
       <TargetPath>models\PP-OCRv6_det_small.onnx</TargetPath>
    </None>
    <None Include="models\PP-OCRv6_rec_small.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
       <TargetPath>models\PP-OCRv6_rec_small.onnx</TargetPath>
    </None>
    <None Include="models\ch_ppocr_mobile_v2.0_cls_mobile.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
       <TargetPath>models\ch_ppocr_mobile_v2.0_cls_mobile.onnx</TargetPath>
    </None>
    <None Include="models\ppocrv6_dict.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
       <TargetPath>models\ppocrv6_dict.txt</TargetPath>
    </None>
  </ItemGroup>  

</Project>
